document.writeln("<div class=\'header\'>");
document.writeln("				<div class=\'container\'>");
document.writeln("					<div class=\'header_left\'>");
document.writeln("						<a href=\'index.html\' class=\'logo pull-left\'><img src=\'img/logo.png\' /></a>");
document.writeln("						<span class=\'pull-left slogan\'>您好，欢迎来到商城！</span>");
document.writeln("					</div>");
document.writeln("					<ul class=\'pull-right hearder-right\'>");
document.writeln("						<li class=\'pull-right\' id=\'cart\'>");
document.writeln("							<a href=\'cart.html\' class=\'gwc\'><span>购物车</span></a>");
document.writeln("						</li>");
document.writeln("						<li class=\'pull-right\' id=\'login\'>");
document.writeln("							<a href=\'login.html\' class=\'pull-right \'>登录</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'pull-right userid\' id=\'usercenter\'>");
document.writeln("							<span id=\'userid\'></span>");
document.writeln("							<div class=\'child \'>");
document.writeln("								<a href=\'UserCenter-info.html\' id=\'usercenterlink\'>个人中心</a>");
document.writeln("								<a href=\'javascript:void(0)\' id=\'exit\'>退出</a>");
document.writeln("							</div>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</div>");